# Form implementation generated from reading ui file 'InfoBubble.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InfoBubble(object):
    def setupUi(self, InfoBubble):
        InfoBubble.setObjectName("InfoBubble")
        InfoBubble.resize(400, 301)
        self.verticalLayout = QtWidgets.QVBoxLayout(InfoBubble)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(9, 9, 9, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textLabel = QtWidgets.QLabel(InfoBubble)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel.sizePolicy().hasHeightForWidth())
        self.textLabel.setSizePolicy(sizePolicy)
        self.textLabel.setText("")
        self.textLabel.setScaledContents(True)
        self.textLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.textLabel.setObjectName("textLabel")
        self.verticalLayout.addWidget(self.textLabel)

        self.retranslateUi(InfoBubble)
        QtCore.QMetaObject.connectSlotsByName(InfoBubble)

    def retranslateUi(self, InfoBubble):
        _translate = QtCore.QCoreApplication.translate
        InfoBubble.setWindowTitle(_translate("InfoBubble", "InfoBubble"))
