# Form implementation generated from reading ui file 'TabContainer.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabContainer(object):
    def setupUi(self, TabContainer):
        TabContainer.setObjectName("TabContainer")
        TabContainer.resize(777, 665)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabContainer.sizePolicy().hasHeightForWidth())
        TabContainer.setSizePolicy(sizePolicy)
        TabContainer.setMouseTracking(True)
        TabContainer.setTabletTracking(True)
        TabContainer.setTabsClosable(True)
        TabContainer.setMovable(False)
        self.ValveOverview = QtWidgets.QWidget()
        self.ValveOverview.setObjectName("ValveOverview")
        TabContainer.addTab(self.ValveOverview, "")
        self.SystemOverview = QtWidgets.QWidget()
        self.SystemOverview.setObjectName("SystemOverview")
        TabContainer.addTab(self.SystemOverview, "")

        self.retranslateUi(TabContainer)
        TabContainer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabContainer)

    def retranslateUi(self, TabContainer):
        _translate = QtCore.QCoreApplication.translate
        TabContainer.setWindowTitle(_translate("TabContainer", "TabWidget"))
        TabContainer.setTabText(TabContainer.indexOf(self.ValveOverview), _translate("TabContainer", "Valve Overview"))
        TabContainer.setTabText(TabContainer.indexOf(self.SystemOverview), _translate("TabContainer", "System Overview"))
