# Form implementation generated from reading ui file 'ValveGUI.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ValveGUI(object):
    def setupUi(self, ValveGUI):
        ValveGUI.setObjectName("ValveGUI")
        ValveGUI.resize(234, 261)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ValveGUI.sizePolicy().hasHeightForWidth())
        ValveGUI.setSizePolicy(sizePolicy)
        ValveGUI.setMinimumSize(QtCore.QSize(150, 150))
        ValveGUI.setSizeIncrement(QtCore.QSize(3, 3))
        ValveGUI.setBaseSize(QtCore.QSize(100, 100))
        ValveGUI.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        ValveGUI.setStyleSheet("QWidget:hover {\n"
"    background-color: rgba(224, 34, 10, 0.3)\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ValveGUI)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.valveImage = QtWidgets.QLabel(ValveGUI)
        self.valveImage.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valveImage.sizePolicy().hasHeightForWidth())
        self.valveImage.setSizePolicy(sizePolicy)
        self.valveImage.setMinimumSize(QtCore.QSize(100, 100))
        self.valveImage.setSizeIncrement(QtCore.QSize(0, 0))
        self.valveImage.setBaseSize(QtCore.QSize(100, 150))
        self.valveImage.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.valveImage.setStyleSheet("")
        self.valveImage.setText("")
        self.valveImage.setScaledContents(True)
        self.valveImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.valveImage.setObjectName("valveImage")
        self.gridLayout.addWidget(self.valveImage, 0, 0, 1, 1)
        self.valveID = QtWidgets.QLabel(ValveGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valveID.sizePolicy().hasHeightForWidth())
        self.valveID.setSizePolicy(sizePolicy)
        self.valveID.setMinimumSize(QtCore.QSize(6, 6))
        self.valveID.setSizeIncrement(QtCore.QSize(3, 3))
        self.valveID.setBaseSize(QtCore.QSize(3, 3))
        self.valveID.setStyleSheet("")
        self.valveID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.valveID.setObjectName("valveID")
        self.gridLayout.addWidget(self.valveID, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(ValveGUI)
        QtCore.QMetaObject.connectSlotsByName(ValveGUI)

    def retranslateUi(self, ValveGUI):
        _translate = QtCore.QCoreApplication.translate
        ValveGUI.setWindowTitle(_translate("ValveGUI", "ValveGUI"))
        self.valveID.setText(_translate("ValveGUI", "Valve ID"))
