# Form implementation generated from reading ui file 'ValveOverview.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ValveOverview(object):
    def setupUi(self, ValveOverview):
        ValveOverview.setObjectName("ValveOverview")
        ValveOverview.resize(716, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ValveOverview.sizePolicy().hasHeightForWidth())
        ValveOverview.setSizePolicy(sizePolicy)
        ValveOverview.setMouseTracking(True)
        ValveOverview.setTabletTracking(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ValveOverview)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ValveOverview)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(ValveOverview)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.valveList = QtWidgets.QListWidget(ValveOverview)
        self.valveList.setEnabled(True)
        self.valveList.setMouseTracking(True)
        self.valveList.setTabletTracking(True)
        self.valveList.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.valveList.setStyleSheet("QListWidget {\n"
"    padding: 9px;\n"
"}")
        self.valveList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.valveList.setAutoScroll(False)
        self.valveList.setAutoScrollMargin(16)
        self.valveList.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.valveList.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.valveList.setDefaultDropAction(QtCore.Qt.DropAction.CopyAction)
        self.valveList.setIconSize(QtCore.QSize(250, 360))
        self.valveList.setMovement(QtWidgets.QListView.Movement.Static)
        self.valveList.setFlow(QtWidgets.QListView.Flow.LeftToRight)
        self.valveList.setProperty("isWrapping", True)
        self.valveList.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.valveList.setLayoutMode(QtWidgets.QListView.LayoutMode.Batched)
        self.valveList.setGridSize(QtCore.QSize(200, 250))
        self.valveList.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        self.valveList.setUniformItemSizes(True)
        self.valveList.setWordWrap(False)
        self.valveList.setSelectionRectVisible(False)
        self.valveList.setObjectName("valveList")
        self.verticalLayout.addWidget(self.valveList)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ValveOverview)
        QtCore.QMetaObject.connectSlotsByName(ValveOverview)

    def retranslateUi(self, ValveOverview):
        _translate = QtCore.QCoreApplication.translate
        ValveOverview.setWindowTitle(_translate("ValveOverview", "ValveOverview"))
        self.label.setText(_translate("ValveOverview", "Område:"))
        self.comboBox.setItemText(0, _translate("ValveOverview", "Test"))
